### PR TITLE
iccv,eccv, old cvpr

### PR DESCRIPTION
**Pull request by skrish13**

### CODE REVIEW

**Comment by dustinvtran** [comment]
Thanks! Can you revert the link change to techtalks.tv? Happy to merge the rest.

**Comment by skrish13** [comment]
The events page was more relevant is what I thought. The homepage wasn't that useful/has old content.. Still wanna revert?

**Comment by dustinvtran** [comment]
Yes. I think the same could be said about videolectures.net and youtube.com. They're more pointers to the homepage than explicit navigational links. In any case, it should be done in a separate PR.

**Comment by skrish13** [comment]
Hmm, okay. Done.

**Pull request merged**
