### PR TITLE
added cvpr 17

### PR DESCRIPTION
**Pull request by skrish13**
There's no single playlist for all videos but playlist for each categories (which is better). So I think it should be okay (even if the same link has prev year's videos)

### CODE REVIEW

**Comment by dustinvtran** [comment]
Thanks. Can you write the full name for CVPR and also write the same bullet point for the year of 2016 (since the same link leads to last year's)?

**Comment by skrish13** [comment]
Yeah, was doing the latter part. Should I expand it to "IEEE Conference on Computer Vision and Pattern Recognition"?

**Comment by dustinvtran** [comment]
"Computer Vision and Pattern Recognition" is fine. Thanks!

**Comment by skrish13** [comment]
Previous year videos didn't really specify which all materials were made available. There were a couple of workshop playlists and not all tutorials were present as well, so didn't mention the details for 2016.

**Comment by dustinvtran** [comment]
Got it. Thanks!

**Pull request merged**
