### PR TITLE
Added mathematicaimonk youtube channel

### PR DESCRIPTION
**Pull request by twkillian**
Dustin,

First off, thanks for putting this together. This will be a fantastic resource that I will utilize and widely share with others. As I've gotten my feet wet in the ML community, the tutorial videos put together by the youtube user mathematicalmonk have been a great way to refresh or introduce basic concepts underpinning much of machine learning. 

I tried my best to adhere to the linking format you put together but wasn't sure if I should include my addition in the current youtube section.

All the best,
Taylor

### CODE REVIEW

**Comment by dustinvtran** [comment]
sure, thanks for contributing. specific youtube channels may be difficult to organize well, similar to recommending specific coursera courses. what about for now, we recommend mathematicaimonk in line with the youtube entry? if there are more youtube channels to look at specifically, perhaps we can organize a sublist within the youtube entry.

**Comment by twkillian** [comment]
Sounds good. 👍 It's tough to create a curated list that is both exhaustive and useful at the same time.

**Comment by dustinvtran** [comment]
note: still happy to merge this PR. just would need to add link/reference to mathematicalmonk inline with the rest of the youtube entry.

**Comment by twkillian** [comment]
Gotcha. I got caught up with some other things yesterday. I'll do it right now.

**Comment by dustinvtran** [comment]
lgtm

**Pull request merged**
